version: '3'
services:
  web:
    build:
      context: ./app
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    # volumes:
    #   - ./app/patent_jsons:/app/patent_jsons  # Mount the JSON data directory as a volume

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    environment:
      - discovery.type=single-node
